# Site/SEO settings
baseurl: ""
google_analytics:
name: "Thoughts. Insights. Life lessons."
title: "Thoughts. Insights. Life lessons."
description: ""
logo: 'assets/images/me1.png'
favicon: 'assets/images/me1.png'
include: ["_pages"]
permalink: /:title/


# Disqus settings
disqus: anandsoni11

# MailChimp settings
mailchimp-list: https://anandsoni.us20.list-manage.com/subscribe/post?u=3aa15cf4404b007d940ede115&amp;id=857d509c42
#mailchimp_input: b_3aa15cf4404b007d940ede115_857d509c42

# Author settings
# Authors
authors:
  anand:
    name: Anand Soni
    display_name: Anand
    gravatar:
    email: anand.92.soni@gmail.com
    web: https://www.anandsoni.in
    twitter: https://twitter.com/anandsonin
    description: ""


# Build settings
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
