# Site/SEO settings
email: anand.92.soni@gmail.com
baseurl: ""
paginate: 12
paginate_path: "/page/:num"
permalink: /:year/:month/:day/:title/
google_analytics:

name: Anand Soni
title: Thoughts. Insights. Life lessons.
description: >
  Pen down the incomprehensibly complex life experiences which will, otherwise, get lost in silence. Forever.
url: http://anandsoni.in
twitter_username: anandsonin
default_img: /assets/images/seo.jpg
social:
  - name: twitter
    url: https://twitter.com/anandsonin
  - name: linkedin
    url: https://www.linkedin.com/in/anand-soni-34846843/
  - name: github
    url: https://github.com/anandsoni11

# Contact settings
contact_img: /assets/images/placeholder-28.jpg
formcarry: https://formcarry.com/s/a_r0zys-qZU

# Disqus settings
disqus: anandsoni11

# MailChimp settings
mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: Anand Soni
    bio: Thomas Vaeth was born in New York, raised in Pennsylvania, and transplanted in Washington. He was a Web Developer at Urban Influence, but now he's a Software Engineer at Getty Images.
    url: http://anandsoni.in

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
